chrome.runtime.onMessage.addListener(
	function(request, sender, sendResponse) {
        const summaryTag = document.getElementById("summary");
		if (summaryTag) summaryTag.remove();
		sendResponse();
	
        let [div, header] = ["div", "h4"].map(element => document.createElement(element));
        const { summary: { result: summary } = {} } = request || {};
        const breakTag = document.createElement("br");
		const description = document.getElementById("above-the-fold");
		
        header.innerHTML="Summary generated by YT-Summarizer: ";
        div.setAttribute("id", "summary");
		div.appendChild(header);
		div.appendChild(breakTag);
		div.appendChild(document.createTextNode(summary));
		description.appendChild(div);
    }
);